mbm/mbm/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from test_app import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url( r'^', include( 'test_app.urls', namespace = 'test_app' ) ),
    url( r'^admin/', admin.site.urls )
]

if settings.DEBUG is True:
    urlpatterns += static( settings.MEDIA_URL, document_root = settings.MEDIA_ROOT )

mbm/test_app/urls.py
from django.conf.urls import url
from test_app import views

app_name = 'test_app'

urlpatterns = [
    url( r'^$', views.Index.as_view(), name = 'index' ),
    url( r'^about/(?P<pk>\d+)$', views.About.as_view(), name = 'about' ),
    url( r'^email/$', views.Email.as_view(), name = 'email' ),
    url( r'^portrait/', views.Gallery.as_view( title = 'portrait', category = 'portrait' ), name = 'portrait' ),
    url( r'^landscape/', views.Gallery.as_view( title = 'landscape', category = 'landscape' ), name = 'landscape' ),
    url( r'^img/new/$', views.ImageCreate.as_view(), name = 'upload' ),
    url( r'^img/success/$', views.ImageSuccess.as_view(), name = 'success' ),
    url( r'^img/(?P<pk>\d+)/$', views.ImageUpdate.as_view(), name = 'update' ),
    url( r'^img/(?P<pk>\d+)/delete/$', views.ImageDelete.as_view(), name = 'delete' ),
    url( r'^login/', views.Login.as_view(), name = 'login' ),
    url( r'^logout/', views.Logout.as_view(), name = 'logout' ),
]

mbm/test_app/models.py
from django.db import models
from django.db.models.signals import post_delete
from django.dispatch.dispatcher import receiver
from django.contrib.auth.models import User
import datetime

# Create your models here.
class Topic( models.Model ):
    tpc_name = models.CharField( max_length = 264, unique = True )

    def __str__( self ):
        return self.tpc_name

class Webpage( models.Model ):
    topic = models.ForeignKey( Topic )
    name = models.CharField( max_length = 264, unique = True )
    url = models.URLField( unique = True )

    def __str__( self ):
        return self.name

class AccessRecord( models.Model ):
    name = models.ForeignKey( Webpage )
    date = models.DateField()

    def __str__( self ):
        return str( self.date )

class ImageUpload( models.Model ):
    PORTRAIT = 'portrait'
    LANDSCAPE = 'landscape'
    CATEGORIES = (
        ( PORTRAIT, 'Portrait'),
        ( LANDSCAPE, 'Landscape' )
    )

    image = models.ImageField( upload_to = 'user_img/' )
    title = models.CharField( max_length = 50 )
    category = models.CharField( max_length = 20, choices = CATEGORIES,
        default = PORTRAIT )
    date = models.DateField( default = '0000-00-00', verbose_name = 'Date (YYYY-MM-DD)')
    camera = models.CharField( max_length = 20 )
    location = models.CharField( max_length = 100 )
    frontpage = models.BooleanField( default = False, verbose_name = 'Display on frontpage?' )

    def __str__( self ):
        return str( self.id )

class EmailRequest( models.Model ):
    sender = models.EmailField( verbose_name = 'Your e-mail')
    sub = models.CharField( max_length = 100, verbose_name = 'Subject' )
    msg = models.TextField( max_length = 1000, verbose_name = 'Message (be nice)' )

class UserProfile( models.Model ):
    ppic = models.ImageField( upload_to = 'ppic/', verbose_name = 'Profile picture' )
    city = models.CharField( max_length = 20 )
    state = models.CharField( max_length = 2 )
    fb = models.URLField( verbose_name = 'Facebook URL' )
    fb_handle = models.CharField( default = 'handle', max_length = 100, verbose_name = 'Facebook name' )
    ig = models.URLField( verbose_name = 'Instagram' )
    ig_handle = models.CharField( default = 'handle', max_length = 100, verbose_name = 'Instagram handle' )
    tw = models.URLField( verbose_name = 'Twitter' )
    tw_handle = models.CharField( default = 'handle', max_length = 100, verbose_name = 'Twitter handle' )
    desc = models.TextField( max_length = 3000, verbose_name = 'About me' )
    cv = models.URLField( default = 'http://google.com', verbose_name = 'Link to resume/CV' )

    def __str__( self ):
        return 'user profile'

@receiver( post_delete, sender = ImageUpload )
def mymodel_delete( sender, instance, **kwargs ):
    # Pass false so FileField doesn't save the model.
    instance.image.delete( False )

mbm/test_app/forms.py
from django import forms
from . import models
from django.contrib.auth.models import User
from django.core import validators

class BootstrapModelForm( forms.ModelForm ):
    def __init__( self, *args, **kwargs ):
        super( BootstrapModelForm, self ).__init__( *args, **kwargs )
        for field in iter( self.fields ):
            self.fields[field].widget.attrs.update( {
                'class': 'form-control'
            })

class UserAuthForm( forms.ModelForm ):
    password = forms.CharField( widget = forms.PasswordInput() )

    class Meta():
        model = models.User
        fields = ( 'username', 'password' )

class EmailForm( BootstrapModelForm ):
    class Meta():
        model = models.EmailRequest
        fields = '__all__'

    def __init__( self, *args, **kwargs ):
        '''
        This use of __init__ changes how Django renders forms which are called with template tags.
        '''
        super( EmailForm, self ).__init__(*args, **kwargs)
        self.fields['sender'].widget.attrs.update( {
            'placeholder': 'tcook@apple.com'
        })
        self.fields['sub'].widget.attrs.update( {
            'placeholder': 'hi'
        })
        self.fields['msg'].widget.attrs.update( {
            'placeholder': 'I love your work'
        })

class UserProfileForm( BootstrapModelForm ):
    class Meta():
        model = models.UserProfile
        fields = '__all__'

class ImageUploadForm( BootstrapModelForm ):
    date = forms.DateField()

    class Meta():
        model = models.ImageUpload
        fields = '__all__'

    def __init__( self, *args, **kwargs ):
        '''
        This use of __init__ changes how Django renders forms which are called with template tags.
        '''
        super( ImageUploadForm, self ).__init__(*args, **kwargs)
        self.fields['frontpage'].widget.attrs.update( {
            'class': ''
        })
        self.fields['date'].widget.attrs.update( {
            'id': 'datepicker'
        })

mbm/test_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.views.generic import View, TemplateView, FormView, ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.base import RedirectView
from django.utils.decorators import method_decorator
from django.conf import settings

from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout

from django.contrib.auth import REDIRECT_FIELD_NAME, login
from django.contrib.auth.forms import AuthenticationForm
from django.urls import reverse, reverse_lazy
from . import forms, models

# Create your views here.

'''
MODELS CALLED IN context_processors.py:
    - UserProfile
'''

class Login( FormView ):
    title = 'login'
    template_name = 'test_app/login/index.html'
    form_class = AuthenticationForm
    redirect_field_name = REDIRECT_FIELD_NAME
    success_url = reverse_lazy( 'test_app:index' )

    def get_context_data( self, **kwargs ):
        title = self.title

        data = super().get_context_data( **kwargs )
        data['title'] = title
        return data

    def form_valid( self, form ):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate( username = username, password = password )

        if user is not None and user.is_active:
            login( self.request, user )
            return super( Login, self ).form_valid( form )
        else:
            return self.form_invalid( form )

class Logout( RedirectView ):
    url = reverse_lazy( 'test_app:index' )

    @method_decorator( login_required )
    def get( self, request, *args, **kwargs ):
        logout( request )
        return super( Logout, self ).get( request, *args, **kwargs )

class About( UpdateView ):
    title = 'about'
    template_name = 'test_app/about/index.html'
    form_class = forms.UserProfileForm
    model = models.UserProfile
    success_url = settings.UPLOAD_SUCCESS_URL

    def get_context_data( self, **kwargs ):
        title = self.title

        data = super().get_context_data( **kwargs )
        data['title'] = title
        data['loggedin'] = self.request.user.is_authenticated
        return data

    def get_success_url( self, **kwargs ):
        return reverse( 'test_app:about',
                        kwargs = { 'pk': self.kwargs['pk'] } )

class Email( CreateView ):
    title = 'email'
    form_class = forms.EmailForm
    model = models.EmailRequest
    template_name = 'test_app/about/email.html'
    success_url = reverse_lazy( 'test_app:index' )

    def get_context_data( self, **kwargs ):
        title = self.title

        data = super().get_context_data( **kwargs )
        data['title'] = title
        return data

    def form_valid( self, form ):
        form.instance.user = self.request.user
        return super( Email, self ).form_valid( form )

    @method_decorator( login_required )
    def dispatch( self, request, *args, **kwargs ):
        return super( Email, self ).dispatch( request, *args, **kwargs )

class Index( ListView ):
    title = 'home'
    template_name = 'test_app/main/index.html'
    model = models.ImageUpload

    def get_context_data( self, **kwargs ):
        title = self.title
        image_objects = self.model.objects.order_by( '-id' ) # all objects in ImageUpload model

        data = super().get_context_data( **kwargs )
        data['title'] = title
        data['images'] = image_objects
        return data

class Gallery( ListView ):
    # to be inherited
    template_name = 'test_app/main/gallery.html'
    model = models.ImageUpload

    # to be overwritten
    title = 'gallery'
    category = None

    def get_context_data( self, **kwargs ):
        title = self.title
        image_objects = self.model.objects.order_by( '-id' ) # all objects in ImageUpload model
        category = self.category

        data = super().get_context_data( **kwargs )
        data['title'] = title
        data['images'] = image_objects
        data['category'] = category
        return data

class ImageCreate( CreateView ):
    title = 'new'
    form_class = forms.ImageUploadForm
    template_name = 'test_app/upload/index.html'
    success_url = reverse_lazy( 'test_app:index' )
    # success_message = 'Image uploaded!'

    def get_context_data( self, **kwargs ):
        title = self.title

        data = super().get_context_data( **kwargs )
        data['title'] = title
        return data

    def form_valid( self, form ):
        form.instance.user = self.request.user
        return super( ImageCreate, self ).form_valid( form )

    @method_decorator( login_required )
    def dispatch( self, request, *args, **kwargs ):
        return super( ImageCreate, self ).dispatch( request, *args, **kwargs )

class ImageUpdate( UpdateView ):
    template_name = 'test_app/img/details.html'
    fields = ( 'title', 'category', 'frontpage' )
    model = models.ImageUpload

    def get_success_url( self, **kwargs ):
        image = self.model.objects.filter( pk = self.kwargs['pk'] ).values()[0]
        if image['category'] == 'portrait':
            print( 'portrait' )
            return reverse_lazy( 'test_app:portrait' )
        elif image['category'] == 'landscape':
            print( 'landscape' )
            return reverse_lazy( 'test_app:landscape' )
        else:
            print( 'default' )
            return reverse_lazy( 'test_app:index' )

    def get_context_data( self, **kwargs ):
        image = self.model.objects.filter( pk = self.kwargs['pk'] ).values()[0] # retrieve pk from url
        title = image['title']

        data = super().get_context_data( **kwargs )
        data['title'] = title
        data['image'] = image
        data['loggedin'] = self.request.user.is_authenticated
        return data

    def form_valid( self, form ):
        form.instance.user = self.request.user
        return super( ImageUpdate, self ).form_valid( form )

class ImageSuccess( TemplateView ):
    template_name = 'test_app/upload/success.html'
    fields = ( 'title', 'category', 'frontpage')
    model = models.ImageUpload

    @method_decorator( login_required )
    def dispatch( self, request, *args, **kwargs ):
        return super( ImageSuccess, self ).dispatch( request, *args, **kwargs )

class ImageDelete( DeleteView ):
    template_name = 'test_app/img/delete.html'
    fields = ( 'title', 'category', 'frontpage' )
    model = models.ImageUpload

    def get_success_url( self, **kwargs ):
        image = self.model.objects.filter( pk = self.kwargs['pk'] ).values()[0] # retrieve pk from url
        if image['category'] == 'portrait':
            print( 'portrait' )
            return reverse_lazy( 'test_app:portrait' )
        elif image['category'] == 'landscape':
            print( 'landscape' )
            return reverse_lazy( 'test_app:landscape' )
        else:
            print( 'default' )
            return reverse_lazy( 'test_app:index' )

    def get_context_data( self, **kwargs ):
        image = self.model.objects.filter( pk = self.kwargs['pk'] ).values()[0] # retrieve pk from url
        title = image['title']

        data = super().get_context_data( **kwargs )
        data['title'] = title
        data['image'] = image
        return data

    @method_decorator( login_required )
    def dispatch( self, request, *args, **kwargs ):
        return super( ImageDelete, self ).dispatch( request, *args, **kwargs )

mbm/templates/test_app/base_styled.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
  <head>
    <meta charset="utf-8">
    <title>silent: {{ title }}</title>

    <!-- Bootstrap 3 CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Custom stylesheet and fonts -->
    <link rel="stylesheet" type="text/css" href="{% static "css/style.css" %}">

    <!-- SM buttons -->
    <link rel="stylesheet"ba href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <!-- Google icons -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- jQuery -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    <!-- Date picker -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

  </head>

  <body>
    <!-- Full sidebar -->
    <div class="container-fluid">
      <div class="row">

       <!-- Main section -->
        <div id="navigation" class="sidebar col-lg-2 col-md-3 col-sm-3">
         <div class="logo">
           <h2><strong><a href="{% url 'test_app:index' %}">i'm silent</a></strong></h2>
         </div>
         <h5>photography</h5><br><br>
           <strong>
           <a href="{% url 'test_app:portrait' %}">portrait</a><br><br>
           <a href="{% url 'test_app:landscape' %}">landscape</a><br><br>
           <a href="{% url 'test_app:about' profile.id %}">about me</a><br><br>
           {% if user.is_authenticated %}
              <br><p>hello, {{ user.username }}</p>
              <a href="{% url 'test_app:upload' %}" class="btn btn-default navbar-btn">upload</a>&nbsp;
              <a href="{% url 'test_app:logout' %}" class="btn btn-warning navbar-btn">logout</a><br>
              {% endif %}<br><br>
           <h4 class="sidebar-section"><i class="material-icons">place</i>&nbsp;<strong>TAMPA, FL
           </strong></h4><br></strong>
        </div>

       <!-- Footer -->
        <div class="sidebar-footer sidebar col-lg-2 col-md-3 col-sm-3 hidden-xs">
         <a href='{{ profile.fb }}'>
           <i class="fa fa-facebook-official" style="font-size:24px"></i>
         </a>
         &emsp;
         <a href='{{ profile.ig }}'>
           <i class="fa fa-instagram" style="font-size:24px"></i>
         </a>
         &emsp;
         <a href='{{ profile.tw }}'>
           <i class="fa fa-twitter" style="font-size:24px"></i>
         </a>
        </div>

        <div class="col-lg-2 col-md-3 col-sm-3 hidden-xs">
          <!-- Placeholder - keep empty -->
        </div>

        <!-- Main content -->
        <div id="main" class="col-lg-10 col-md-9 col-sm-9">
          {% block main_body %}
          {% endblock %}
        </div>
      </div>
    </div>

    <!-- Bootstrap 3 JavaScript-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <!-- Date picker -->
    <script>
      $( function() {
        $( "#datepicker" ).datepicker();
      } );
    </script>

    <!-- Lazy Load -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.lazyload/1.9.1/jquery.lazyload.min.js"></script>
    <script>
      $( 'img.lazy' ).lazyload( {
        effect: 'fadeIn',
      } );
    </script>
  </body>
</html>

mbm/templates/test_app/email.html
<!DOCTYPE html>
{% extends "test_app/base_styled.html" %}
{% load staticfiles %}

{% block title_head %}
  <title>silent: new post</title>
{% endblock %}

{% block main_body %}
  <div class="col-xs-8 col-xs-offset-2">
    <div class="container-fluid">
      <div class="page-header">
        <h1>Send an e-mail</h1>
      </div>

      {{ form.as_p }}
      <input type="submit" class="btn btn-primary" name="" value="Submit">
      {% csrf_token %}
    </div>
  </div>
{% endblock %}